# Generated by Django 2.0.1 on 2008-01-01 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0002_auto_20080101_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemadvert',
            name='Asking_Price',
        ),
    ]
