# Generated by Django 2.0.1 on 2008-01-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0003_remove_itemadvert_asking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemadvert',
            name='Asking_Price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
