# Generated by Django 2.0.1 on 2008-01-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0004_itemadvert_asking_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemadvert',
            name='Seller_Name',
            field=models.CharField(max_length=50),
        ),
    ]
