# Generated by Django 2.0.1 on 2008-01-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0006_auto_20080101_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemadvert',
            name='Phone_Number',
            field=models.FloatField(null=True),
        ),
    ]
