# Generated by Django 2.0.1 on 2018-06-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0007_auto_20080101_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemadvert',
            name='Asking_Price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='itemadvert',
            name='Phone_Number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
