# Generated by Django 2.0.1 on 2018-06-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0008_auto_20180609_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemadvert',
            name='Item',
            field=models.CharField(max_length=100),
        ),
    ]
