# Generated by Django 2.0.1 on 2018-06-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0009_auto_20180609_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemadvert',
            old_name='Created_data',
            new_name='Created_date',
        ),
    ]
