# Generated by Django 2.0.1 on 2018-07-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0010_auto_20180622_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemadvert',
            name='Location',
        ),
        migrations.AddField(
            model_name='itemadvert',
            name='Category',
            field=models.CharField(choices=[('PH', 'Phone'), ('LP', 'Laptop'), ('HS', 'Hostel_Space'), ('BK', 'Books'), ('FR', 'Furniture'), ('EL', 'Electronics')], default='PH', max_length=2),
        ),
        migrations.AlterField(
            model_name='itemadvert',
            name='Asking_Price',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='itemadvert',
            name='Phone_Number',
            field=models.CharField(help_text='Please input a working line that you can be contacted with', max_length=11),
        ),
    ]
