# Generated by Django 2.0.1 on 2018-07-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0011_auto_20180725_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemadvert',
            name='Phone_Number',
            field=models.CharField(help_text='Please input a working line that you can be contacted with', max_length=11, null=True),
        ),
    ]
