# Generated by Django 2.0.1 on 2018-08-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0013_auto_20180726_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemadvert',
            name='Asking_Price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='itemadvert',
            name='Phone_Number',
            field=models.CharField(help_text='Please input a working line that you can be contacted with', max_length=11),
        ),
    ]
