# Generated by Django 2.0.1 on 2018-08-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0014_auto_20180805_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemadvert',
            name='Asking_Price',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
