# Generated by Django 2.0.1 on 2018-08-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0015_auto_20180805_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemadvert',
            name='Asking_Price',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
