# Generated by Django 2.0.1 on 2018-08-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0016_auto_20180806_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemadvert',
            name='Location',
            field=models.CharField(choices=[('H3', 'Hall3'), ('H4', 'Hall4'), ('H2', 'Hall2'), ('MG', 'Main_gate'), ('H1', 'Hall1')], default='H3', max_length=2),
        ),
        migrations.AlterField(
            model_name='itemadvert',
            name='Asking_Price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='itemadvert',
            name='Description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='itemadvert',
            name='published_date',
            field=models.DateTimeField(),
        ),
    ]
