# Generated by Django 2.0.1 on 2018-08-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0017_auto_20180810_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemadvert',
            name='Item',
        ),
        migrations.AlterField(
            model_name='itemadvert',
            name='Phone_Number',
            field=models.CharField(help_text='**Please input a working line that you can be contacted with', max_length=11),
        ),
    ]
