# Generated by Django 2.0.1 on 2018-08-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0019_auto_20180813_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemadvert',
            name='Image',
            field=models.ImageField(default=1, height_field=60, upload_to='', width_field=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemadvert',
            name='Phone_Number',
            field=models.CharField(help_text='<p style="color: red; font: italic 12px tahoma;">**Please input a working Phone Number that you can be contacted with on the fly</p>', max_length=11),
        ),
    ]
