# Generated by Django 2.0.1 on 2018-08-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0020_auto_20180817_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemadvert',
            name='Image',
            field=models.ImageField(height_field=60, upload_to='uploads', width_field=40),
        ),
    ]
