# Generated by Django 2.0.1 on 2018-08-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0023_auto_20180817_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemadvert',
            name='Category',
            field=models.CharField(choices=[('PHONE', 'Phone'), ('LAPTOP', 'Laptop'), ('HS', 'Hostel_Space'), ('BOOKS', 'Books'), ('FURNITURE', 'Furniture'), ('ELECTRONICS', 'Electronics')], default='PHONE', max_length=15),
        ),
        migrations.AlterField(
            model_name='itemadvert',
            name='Location',
            field=models.CharField(choices=[('HALL3', 'Hall3'), ('HALL4', 'Hall4'), ('HALL2', 'Hall2'), ('MAINGATE', 'Main_gate'), ('HALL1', 'Hall1')], default='HALL3', max_length=2),
        ),
    ]
