# Generated by Django 2.0.1 on 2018-08-21 09:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0024_auto_20180817_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seller_Name', models.CharField(max_length=50)),
                ('Phone_Number', models.CharField(help_text='<p style="color: red; font: italic 12px tahoma;">**Please input a working Phone Number that you can be contacted with on the fly</p>', max_length=11)),
                ('Item', models.CharField(max_length=20)),
                ('Location', models.CharField(choices=[('HALL3', 'Hall3'), ('HALL4', 'Hall4'), ('HALL2', 'Hall2'), ('MAINGATE', 'Main_gate'), ('HALL1', 'Hall1')], default='HALL3', max_length=10)),
                ('Description', models.TextField(max_length=250)),
                ('Asking_Price', models.CharField(max_length=20)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Category_Logo', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ItemAdvert',
        ),
        migrations.AddField(
            model_name='advert',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campusbuy.Category'),
        ),
    ]
