# Generated by Django 2.0.1 on 2018-08-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0025_auto_20180821_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Category_Logo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='Name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
