# Generated by Django 2.0.1 on 2018-08-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0026_auto_20180822_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Category_Logo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='Name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
