# Generated by Django 2.0.1 on 2008-01-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0027_auto_20180822_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Category_Logo',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
