# Generated by Django 2.0.1 on 2008-01-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0028_auto_20080105_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Details',
            field=models.CharField(default='Default', max_length=30),
        ),
    ]
