# Generated by Django 2.0.1 on 2008-01-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0029_category_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Details',
            field=models.CharField(default='Default', max_length=100),
        ),
    ]
