# Generated by Django 2.0.1 on 2019-03-03 14:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0032_auto_20181221_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='Asking_Price',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='advert',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='Category_Logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Category_Logo'),
        ),
    ]
