# Generated by Django 2.0.1 on 2019-04-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0033_auto_20190303_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='Asking_Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='advert',
            name='Location',
            field=models.CharField(choices=[('H4', 'Hall4'), ('H3', 'Hall3'), ('H2', 'Hall2'), ('H1', 'Hall1'), ('MG', 'Main gate'), ('GP', 'Green Park'), ('GTBWS', 'GTBank Wifi Spot'), ('NAASG', 'Naas Garden'), ('PSC', 'Physical Science Complex'), ('MSC', 'Medical Science Complex'), ('ORC', 'Orchard'), ('J12', 'June12')], default='H3', help_text='<p style="color: red; font: italic 12px tahoma;">**Choose a location where you can easily meet up with potential buyers</p>', max_length=10),
        ),
        migrations.AlterField(
            model_name='advert',
            name='Phone_Number',
            field=models.IntegerField(help_text='<p style="color: red; font: italic 12px tahoma;">**Please input a working Phone Number that you can be contacted with on the fly</p>'),
        ),
    ]
