# Generated by Django 2.0.1 on 2019-04-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0034_auto_20190415_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='Asking_Price',
            field=models.CharField(max_length=20),
        ),
    ]
