# Generated by Django 2.0.1 on 2019-05-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0035_auto_20190415_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='image',
        ),
        migrations.AlterField(
            model_name='advert',
            name='Asking_Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='advert',
            name='Phone_Number',
            field=models.CharField(max_length=12),
        ),
    ]
