# Generated by Django 2.0.1 on 2019-06-01 05:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0036_auto_20190511_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advert',
            name='Location',
            field=models.CharField(choices=[('HALL4', 'Hall4'), ('HALL3', 'Hall3'), ('HALL2', 'Hall2'), ('HALL1', 'Hall1'), ('MAIN_GATE', 'Main gate'), ('GREEN_PARK', 'Green Park'), ('GTBANK', 'GTBank Wifi Spot'), ('NAAS_GARDEN', 'Naas Garden'), ('PHYSICAL_SCIENCE_COM', 'Physical Science Complex'), ('MED_COM', 'Medical Science Complex'), ('BASEMENT', 'Basement'), ('JUNE12', 'June12'), ('ENGINEERING_PARK', 'Engineering Park')], default='HALL3', help_text='<p style="color: red; font: italic 12px tahoma;">**Choose a location where you can easily meet up with potential buyers</p>', max_length=10),
        ),
    ]
