# Generated by Django 2.0.1 on 2019-08-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbuy', '0037_auto_20190601_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='Item',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='advert',
            name='Location',
            field=models.TextField(choices=[('HALL4', 'Hall4'), ('HALL3', 'Hall3'), ('HALL2', 'Hall2'), ('HALL1', 'Hall1'), ('MAIN_GATE', 'Main gate'), ('GREEN_PARK', 'Green Park'), ('GTBANK', 'GTBank Wifi Spot'), ('NAAS_GARDEN', 'Naas Garden'), ('PHYSICAL_SCIENCE_COM', 'Physical Science Complex'), ('MED_COM', 'Medical Science Complex'), ('BASEMENT', 'Basement'), ('JUNE12', 'June12'), ('ENGINEERING_PARK', 'Engineering Park')], default='HALL3', help_text='<p style="color: red; font: italic 12px tahoma;">**Choose a location where you can easily meet up with potential buyers</p>', max_length=250),
        ),
    ]
